services:
  yourdailyboard_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yourdailyboard_backend
    image: yourdailyboard_backend
    env_file:
      - path: ./.env
        required: true
    environment:
      NODE_ENV: ${NODE_ENV}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SECRET_KEY: ${SECRET_KEY}
      PORT: ${PORT}
      ROOT_URL: ${ROOT_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - '${PORT}:${PORT}'
    command: >
      bash -c "node ./build/src/config/setup-database.js && ./build/src/entrypoint.sh"
    volumes:
      - sqlite_data:/app/build/src/database/sqlite # use named volume to persist sqlite file
      - ./logs:/app/logs # Persist combined logs
      - ./error-logs:/app/error-logs # Persist error logs

volumes:
  sqlite_data:
