name: test-backend

on: push

env:
  DB_DATABASE: test
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_USER: root
  DB_PASSWORD: root
  DB_TYPE: development

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Set up database
        uses: samin/mysql-action@v1
        with:
          mysql root password: root

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run database migrations
        run: npm run knex migrate:latest
        working-directory: ./backend

      - name: Run jest
        run: npm test
        working-directory: ./backend

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run lint
        run: npm run lint
        working-directory: ./backend
