name: test-backend

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  DB_DATABASE: your_daily_board
  DB_USER: root
  DB_PASSWORD: root

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run lint
        run: npm run lint
        working-directory: ./backend

  jest:
    runs-on: ubuntu-20.04

    steps:
      - name: Prepare database
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run database migrations
        run: npm run knex migrate:latest
        working-directory: ./backend

      - name: Run jest
        run: npm test
        working-directory: ./backend
